# -*- coding: utf-8 -*-
"""player.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AirUQzmYg84uIHzRBO5K9C8hHB_AFVjg

# INFOMTALC 2026: Midterm assignment 1
## Transformer-based chess player

## 1. General set-up
This Colab contains a description of one of the exercises for your midterm assignment. In this exercise, you will need to write a transformer-based chess player!  

That is, you will need to implement a class called `TransformerPlayer` -- a chess player that will look at a chess board and produce a move. Players submitted by all students will play in a championship against each other and against some baseline players that we will inject into the championship. The championship will result in a leaderboard, and points will be assigned based on this leaderboard and validation checks.

The idea behind this assignment is not chess: at least one of the authors of this assignment can barely remember how figures move. This is an artificial case of an in-domain problem that has to be approached with a particular toolbox -- in our case, transformer-based models. In fact, chess is a great example of a task that can be seen as a text task: both the state of the board and the move can be represented as text sequences (we will talk about the format below).

You are free to choose the architecture and the approach yourself. For instance, maybe you want an encoder model to classify board states into as many classes as there are available moves? Maybe you want a decoder model to continue the board-state sequence with what the next move should be? Or an encoder-decoder model to translate board states into moves? It's up to you.

Whether you want to do some training or make creative use of already existing transformer models is up to you as well. **It is not allowed** to use already trained specialized chess transformer models (there are some on HF). To check for that, we will require you to submit a link to the model you are using on HF. So, you will be **required** to push your model to HF if you are doing some additional training.

If you're doing training, again, you take care of where to get the data. There are existing datasets, or you can decide to generate your dataset yourself based on some helping code we provide below.

Ok, enough of general description, let's move on to something more concrete. We pre-wrote some code to orchestrate this assignment and to help you. Clone the repository and install everything:
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/bylinina/chess_exam.git
# %cd /content/chess_exam
!pip install -e .

from chess_tournament import (
    Game,
    Player,
    RandomPlayer,
    LMPlayer,
    SmolPlayer,
    EnginePlayer,
    run_tournament
    )

"""To make things more structured, we made a `Player` class that all players inherit from. All it has is a built-in `.get_move()` method:

```python
class Player(ABC):
    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def get_move(self, fen: str) -> Optional[str]:
        pass
```

Now, one of our baseline players will be the RandomPlayer. It is defined based on Player but now the mechanics of producing a move given an input position is defined as well (it just produces a random move from the set of valid moves given a position):

```python
class RandomPlayer(Player):
    def get_move(self, fen: str) -> Optional[str]:
        board = chess.Board(fen)
        moves = list(board.legal_moves)
        return random.choice(moves).uci() if moves else None
```

As you see, it takes a string as input and produces either a random legal move or None if there are no legal moves available.

Time to talk about **the input sequence** -- board state. We are using the standard **FEN notation**. It's a line of text that fully describes the state of the board. Read more about it [here](https://www.chess.com/terms/fen-chess). For example, this:

```8/8/8/4p1K1/2k1P3/8/8/8 b - - 0 1```

corresponds to this:

<img src="https://images.chesscomfiles.com/uploads/v1/images_users/tiny_mce/pdrpnht/phpdAnlDc.png" width="200"/>

The moves have [UCI format](https://en.wikipedia.org/wiki/Universal_Chess_Interface), for instance:

- e2e4
- e7e5

Now, in order for the players to actually play, we need to initialize them. Let's make two instances of random player, to see how they will play with each other. We have to give each of them a name:
"""

random1 = RandomPlayer("Random-1")
random2 = RandomPlayer("Random-2")

"""In order to execute the game, we give you the `Game` class. It orchestrates the exchange of board states and moves between the players. Most importantly, it has the `play` method that runs the game! Here is how it works: you give it two player instances, along with an optional `max_half_moves` parameter so that it doesn't go on for too long (there's a default, just in case).

Then you play the game! There are behavioral controls there as well(`verbose` parameter to tell it whether to print out intermediate steps; `log_moves` to print a short log per move -- useful if you want to generate training data!!; `log_to_file` to pass the log file name if you want it; feel free to explore the code in the repo as well):
"""

game = Game(random1, random2, max_half_moves=50)
game.play()

game.play(log_moves=True, log_to_file='log.csv')

"""You might notice the `fallback:Bool` part of the log. It's there to keep track of the times the player either outputs an illegal move or doesn't produce a move (outputs `None`) and the list of available moves is not empty. In this case, `Game` generously falls back to a mechanism that picks a random legal move instead of recording that the player simply lost.

Note that our `Random` players are actually pretty strong -- at least they always produce a legal move! So it's a solid baseline in a situation when fallback counts are taken into account for ranking (and we **will** take them into account -- otherwise a solid strategy for your player would be to simply always output `None` to induce a fallback).

Feel free to use our `Random` player to test your player against! But we have more players for you to play with.

## 2. Pre-made baseline players

We have pre-made some player classes you can practice against:
- `RandomPlayer` (you saw it above)
- `EnginePlayer`
- `LMPlayer`
- `SmolPlayer`

### EnginePlayer

`EnginePlayer` uses a very strong chess player engine available via an API. You can't base your submission on it -- but we will inject two versions of this player into our championship. It runs with a free API so it sometimes limits the number of calls and can produce fallbacks. Even with that, it's **very strong**! We make it weaker by manipulating the probability it produces its second-best move and a random move.

If you want to use it, you can get a free API key for StockFish16 chess engine via [RapidAPI](https://rapidapi.com/cinnamon17/api/Chess%20StockFish%2016%20API) (to see your API key press the blue 'Test endpoint' button). Then input your API key here and you're ready to go:
"""

from getpass import getpass
import os

os.environ["RAPIDAPI_KEY"] = getpass("RapidAPI key:")

engine_strong = EnginePlayer("Stockfish-Strong", blunder_rate=0.0, ponder_rate=0.05)
engine_weak = EnginePlayer("Stockfish-Weak", blunder_rate=0.25, ponder_rate=0.65)

game = Game(engine_strong, random1, max_half_moves=200) # 200 is a more useful number of moves than 50 we had before, but will take longer
game.play() # --> (string of the outcome, points gained per player, fallback count)

"""### LMPlayer

Here is a super-quick baseline LM player: just a quantized big-ish LM -- `mistralai/Mistral-7B-Instruct-v0.2` -- with a couple of tricks to reduce the rate of illegal moves produced (try `n` times before outputting `None`, some prompt-play). Don't use this class for your submissions! Your class should inherit directly from `Player`, not from `LMPlayer`. This one doesn't load the model very efficiently, so it's just for you to play against if you want.
"""

lm = LMPlayer("Mistral-7B")

Game(engine_strong, lm).play()

"""### SmolPlayer

This baseline player is using a waaaay larger model (`moonshotai/Kimi-K2-Instruct`) that's accessed via Inference API, but without any bells and whistles and postprocessing. In order to use this player, you need a HF token, and small costs might be incurred. If you can't use this player, no worries -- you don't really need it, it's just for illustration and for you to try your player against. It will, however, enter the championship as a baseline!

**You can't use this kind of player in your submission**: Your models have to be running on a free-tier Colab locally! Otherwise, it'd be a competition of API costs you are willing to allocate -- huge models are probably pretty good out of the box (maybe you can use them for your data generation though? up to you)
"""

os.environ["HF_TOKEN"] = getpass("HF token:")

kimi = SmolPlayer("Kimi")
Game(kimi, lm).play()

"""## 3. Submission and grading

### 3.1 Submit your player!

Your submission for this exercise will happen via **[Google Forms here](https://forms.gle/Cg425deqMeYF5ujRA)**. You will need to fill in:
- your first and last name,
- student number
- the link to the GitHub repository with your player class (in this format: `https://github.com/<USERNAME>/<REPO_NAME>.git`)
- the link to the HF model card for the transformer model that is the basis of your player
- (+ some additional info about your solution)

It is very important that:
- Your repository contains a file with the name `player.py`
- In that file, you define a class that has the name `TransformerPlayer`
- That class inherits from the class `Player`
- That class contains the `get_move()` method
- Your repository contains the `requirements.txt` file with all packages that need to be installed in a standard Colab setting
- Your player has to be initializable with just the name as the only argument (`player = TransformerPlayer("Student")` or something like that -- so the rest of the arguments have to be set by default)

If your `TransformerPlayer` doesn't pass these tests (they will be automatic), your player will be disqualified. In order to help you, we created a template repo that passess all the tests. You can just fork it or clone it or just copy the code and work with it and then use the result for your submission: https://github.com/bylinina/chess_player_template.git

### 3.2 Get your rating and grade

- If your player is disqualified, you get 0 points
- If your player participates in the championship, your grade will be defined by the distribution of the players in the leaderboard with respect to each other and with respect to the injected baselines
- If you want to know the details of how the validation and championships will be done, check out [this Colab with a fake trial run](https://colab.research.google.com/drive/1IeLAYsjcWuorTd7JXV8TNfxQvmzewzfe?usp=sharing). We are most likely to run it again, as is.
- We will share the leaderboard and results as soon as we have them!

### 3.3 Tips, dos and don'ts
- Our transormer-based example players are all built on decoder-only models. Not because they are necessarily better! But just because it was the fastest things to assemble. Don't feel the need to only work with decoders -- as long as you can make the model output a string, it's fine -- it can be an encoder class label
- Just to reiterate: Don't use pre-trained **chess transformer** models! We will check
- Don't make 'dummy players' that always ouput `None` and therefore default to the `RandomPlayer` strong baseline. We will check
- You don't have to train / fine-tune a model yourself. You can find ways to strengthen a general LM by all sorts of tricks: prompting, comparing probabilities of competitor output strings (check out the [`minicons`](https://github.com/kanishkamisra/minicons) library that might be useful), enforcing the output format (check out the [`lm-format-enforcer`](https://github.com/noamgat/lm-format-enforcer) library) -- anything!
- You might as well want to fine-tune! Models that you can fine-tune in a Colab would be smaller than the ones that can fit the Colab for inference, but maybe specialized knowledge beats size? We don't know! If you want to train, you are free to search data anywhere you want: there are existing datasets, but also you can use the existing player baselines as a means of generating board+move data.
- If you fine-tune a model, you have to make it public on HF, otherwise the championship won't work. Push it it HF.


Ok, that's all! Best of luck!! (Maybe we'll participate too, who knows)
"""

#log in with my token from Hugging face
from huggingface_hub import login
login()

#making sure transformers run on the latest model to avoid collapses
!pip install git+https://github.com/huggingface/transformers.git

"""After running the upgrade commands above, please re-run the cells to initialize the tokenizer and model (cells `760AEb3VGU6g`, `yRrZn7GUgz7o`, and `Of_N5qhviQKM`) to see if the issue is resolved."""

from __future__ import annotations

import os
import re
import random
from typing import Optional, List

import chess
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig


_UCI_RE = re.compile(r"\b([a-h][1-8][a-h][1-8][qrbn]?)\b", re.IGNORECASE)


class TransformerPlayer(Player):
    """
    Transformer-based chess player.
    - Input: FEN string
    - Output: UCI move string (e.g., 'e2e4', 'e7e8q') or None if no legal moves
    """

    def __init__(
        self,
        name: str,
        model_name: str = "Qwen/Qwen3.5-4B",
        seed: int = 42,
        use_4bit: bool = True,
        max_new_tokens: int = 8,
        temperature: float = 0.2,
        top_p: float = 0.9,
    ):
        super().__init__(name)

        random.seed(seed)
        self.model_name = model_name
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p

        # Device + model loading (4-bit since possible to fit in Colab)
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True, trust_remote_code=True)

        quant_cfg = None
        if use_4bit:
            quant_cfg = BitsAndBytesConfig(       #preventing model from failing due to the new 4bit syntax
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=torch.float16,
                bnb_4bit_use_double_quant=True,
            )

        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            device_map="auto",
            quantization_config=quant_cfg,
            trust_remote_code=True,
        )
        self.model.eval()

    def _legal_moves_uci(self, board: chess.Board) -> List[str]:
        return [m.uci() for m in board.legal_moves]

    def _build_prompt(self, fen: str, legal_moves: List[str]) -> str:
        # Keep prompt short-ish (speed) but strict (format)
        return (
            "You are a super powerful chess engine."
            "Given this chess position in FEN:\n"
            f"{fen}\n\n"
            "Choose exactly ONE move from the following LEGAL moves (UCI):\n"
            f"{', '.join(legal_moves)}\n\n"
            "Return ONLY the move in UCI format. No explanation."
        )

    def _extract_uci(self, text: str) -> Optional[str]:
        text = text.strip().lower()
        m = _UCI_RE.search(text)
        return m.group(1).lower() if m else None

    def get_move(self, fen: str) -> Optional[str]:
        board = chess.Board(fen)
        legal = self._legal_moves_uci(board)
        if not legal:
            return None

        prompt = self._build_prompt(fen, legal)

        inputs = self.tokenizer(prompt, return_tensors="pt")
        inputs = {k: v.to(self.model.device) for k, v in inputs.items()}

        pad_id = self.tokenizer.pad_token_id or self.tokenizer.eos_token_id

        try:
            out = self.model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=True,
                temperature=self.temperature,
                top_p=self.top_p,
                pad_token_id=pad_id,
            )
            text = self.tokenizer.decode(out[0], skip_special_tokens=True)
            move = self._extract_uci(text)

            # Strict legality check (prevents illegal moves)
            if move in legal:
                return move

        except Exception:
            # If model generation fails for any reason, fall back safely
            pass

        # Safe fallback to guarantee a legal move
        return random.choice(legal)

from __future__ import annotations #to use Optional[str] hints

import re     #to extract UCI move from model text
import random   #to never crash/return illegal
from typing import Optional, List, Tuple

import chess #to read FEN, generate legal moves etc..
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

_UCI_RE = re.compile(r"\b([a-h][1-8][a-h][1-8][qrbn]?)\b", re.IGNORECASE) #allowed moves formation


class TransformerPlayer(Player):

   """
   Transformer-based chess player.
    - Input: FEN string
    - Output: UCI move string (e.g., 'e2e4', 'e7e8q') or None if no legal moves

    Upgrade: candidate scoring (reranking) over legal moves for stronger, more stable play.
   """
   def __init__(
        self,
        name: str,
        model_name: str = "Qwen/Qwen3.5-4B",
        seed: int = 123,  #ensure repeatble results
        use_4bit: bool = True,  #use model in 4-bit to fit in Colab GPU memory
        # generation fallback params
        max_new_tokens: int = 8,
        temperature: float = 0.2,
        top_p: float = 0.9,
        # candidate scoring params for strengthening machine
        use_candidate_scoring: bool = True,     #if true, score a legal move instead of randomly generated
        max_candidates: int = 48,     #score only top N legal moves
        score_batch_size: int = 8,     #batch size for scoring
    ):
        super().__init__(name)

        random.seed(seed)
        self.model_name = model_name

        # Backup generation settings (only used if scoring fails)
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p

        # Candidate scoring settings
        self.use_candidate_scoring = use_candidate_scoring
        self.max_candidates = max_candidates
        self.score_batch_size = score_batch_size

        # Tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            use_fast=True,
            trust_remote_code=True,
        )

        # (4-bit) to avoid syntax mismatch
        quant_cfg = None
        if use_4bit:
            quant_cfg = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=torch.float16, #speed
                bnb_4bit_use_double_quant=True,   #extra compression trick
            )

        # Load actual model
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            device_map="auto",
            quantization_config=quant_cfg,
            trust_remote_code=True,
        )
        self.model.eval()

    # Utilities
   def _legal_moves_uci(self, board: chess.Board) -> List[str]:
        return [m.uci() for m in board.legal_moves]   # convert python-chess Move objects to UCI strings

   def _extract_uci(self, text: str) -> Optional[str]:
        text = text.strip().lower()
        m = _UCI_RE.search(text)
        return m.group(1).lower() if m else None


    # Candidate scoring!
   def _candidate_subset(self, board: chess.Board, legal_uci: List[str]) -> List[str]:
        """
        We don't score ALL legal moves (could be 30-80). It's slow.
        So we keep "more important" moves first:
        promotions > checks > captures > castles > others
        """
        moves = [chess.Move.from_uci(m) for m in legal_uci]

        promos, captures, castles, others = [], [], [], []
        for mv in moves:
            if mv.promotion is not None:
                promos.append(mv) #to ensure pawn promotion is taken into considertion
            elif board.is_capture(mv):
                captures.append(mv)   #critical captures
            elif board.is_castling(mv):
                castles.append(mv)    #castling for king safety
            else:
                others.append(mv)

        checks = []   #this chunk to temporarily play the move and undo it if move gives check
        for mv in moves:
            board.push(mv)
            if board.is_check():
                checks.append(mv)
            board.pop()

        ranked = promos + checks + captures + castles #priority order
        seen = set(ranked)
        ranked += [m for m in others if m not in seen]

        ranked_uci = [m.uci() for m in ranked]
        if len(ranked_uci) > self.max_candidates:
            ranked_uci = ranked_uci[: self.max_candidates]
        return ranked_uci     #list of moves we will actually score

   def _build_scoring_prompt(self, fen: str) -> str:
        # Keep stable and short, this promt is the same for all candidates.
        return (
            "You are a strong chess player.\n"
            "Given this position in FEN:\n"
            f"{fen}\n\n"
            "Best move in UCI:"
        )

   @torch.no_grad()
   def _score_candidates(self, prompt: str, candidates: List[str]) -> List[float]:
        """
        Score each candidate by mean log-prob of its tokens as continuation of the prompt.
        The higher the score, the more model prefers that candidate.
        """
        scores: List[float] = []

        # Prompt length in tokens (candidate starts after this)
        prompt_ids = self.tokenizer(prompt, return_tensors="pt")["input_ids"].to(self.model.device)
        prompt_len = prompt_ids.shape[1]
 # Score candidates in batches (faster on GPU)
        for i in range(0, len(candidates), self.score_batch_size):
            batch = candidates[i : i + self.score_batch_size]
            texts = [f"{prompt} {c}" for c in batch]  # prompt and after a candidate, since leading space helps tokenization

            enc = self.tokenizer(texts, return_tensors="pt", padding=True)
            enc = {k: v.to(self.model.device) for k, v in enc.items()}

            input_ids = enc["input_ids"]
            attention_mask = enc["attention_mask"] #1 for real tokens, 0 for padding

            out = self.model(input_ids=input_ids, attention_mask=attention_mask)  #forward pass
            logits = out.logits  # raw model scores for next token (B, T, V)
            logprobs = torch.log_softmax(logits, dim=-1)

            for b in range(input_ids.shape[0]):
                ids = input_ids[b]
                mask = attention_mask[b]
                end = int(mask.sum().item())  # non-pad end
                start = prompt_len

                # If something weird happens and we have no candidate tokens
                if start >= end:
                    scores.append(-1e9)
                    continue

                # Candidate tokens are ids[start:end]
                tok = ids[start:end]
                # Pred positions are start-1 ... end-2
                pred_pos = torch.arange(start - 1, end - 1, device=self.model.device)

                lp = logprobs[b, pred_pos, tok]  # (cand_len,)
                scores.append(lp.mean().item())  # length-normalized

        return scores

   def _pick_best_scored_move(self, board: chess.Board, fen: str, legal: List[str]) -> Optional[str]:
        prompt = self._build_scoring_prompt(fen)
        candidates = self._candidate_subset(board, legal)
        if not candidates:
            return None

        cand_scores = self._score_candidates(prompt, candidates)
        best_idx = max(range(len(candidates)), key=lambda k: cand_scores[k])
        best_move = candidates[best_idx]
        return best_move if best_move in legal else None

        # Generation fallback to avoid illegal moves
   def _build_generation_prompt(self, fen: str, legal_moves: List[str]) -> str:
        return (
            "You are an extremely powerful chess engine.\n"
            "Given this chess position in FEN:\n"
            f"{fen}\n\n"
            "Choose exactly ONE move from the following LEGAL moves (UCI):\n"
            f"{', '.join(legal_moves)}\n\n"
            "Return ONLY the move in UCI format. No explanation."
        )

   def _generate_move(self, fen: str, legal: List[str]) -> Optional[str]:
        prompt = self._build_generation_prompt(fen, legal)
        inputs = self.tokenizer(prompt, return_tensors="pt")
        inputs = {k: v.to(self.model.device) for k, v in inputs.items()}

        pad_id = self.tokenizer.pad_token_id or self.tokenizer.eos_token_id

        out = self.model.generate(
            **inputs,
            max_new_tokens=self.max_new_tokens,
            do_sample=True,
            temperature=self.temperature,
            top_p=self.top_p,
            pad_token_id=pad_id,
        )
        text = self.tokenizer.decode(out[0], skip_special_tokens=True)
        move = self._extract_uci(text)
        return move if move in legal else None

     # main required method
   def get_move(self, fen: str) -> Optional[str]:
        board = chess.Board(fen)    #create board from fen
        legal = self._legal_moves_uci(board)  #list legal moves
        if not legal:
            return None

        # main: candidate scoring
        if self.use_candidate_scoring:
            try:
                best = self._pick_best_scored_move(board, fen, legal)
                if best is not None:
                    return best
            except Exception:
                # if scoring fails, fall back to generation / random
                pass

        # backup: generate + validate
        try:
            move = self._generate_move(fen, legal)
            if move is not None:
                return move
        except Exception:
            pass

        # last resort: random legal move
        return random.choice(legal)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,     #defining new bit config (4bit) for new syntax off model load
    bnb_4bit_use_double_quant=True
)
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3.5-4B")
model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen3.5-4B",
    device_map="auto",
    quantization_config=bnb_config
    )

my_player = TransformerPlayer("Student")   # must work with name only

game = Game(my_player, random2, max_half_moves=200)
result = game.play(2)
result

import time
start = time.time()
#statistics on multiple games to see strengths of my Student player
wins = 0
draws = 0
losses = 0

for i in range(5):
    game = Game(my_player, random1, max_half_moves=200)
    outcome, points, fallback = game.play()

    if outcome == "1-0":
        wins += 1
    elif outcome == "0-1":
        losses += 1
    else:
        draws += 1

wins, draws, losses
end = time.time()
print("Time:", end-start, "seconds")

wins, draws, losses

game.play(log_moves=True, log_to_file='log.csv')